extends Node

func run(h: Node, game: Node2D) -> void:
	var original := Session.snapshot()
	h.check(Session.commit() == OK, "Challenge fixture uses an isolated saved campaign")
	var save_bytes := FileAccess.get_file_as_bytes(Session.save_path) if FileAccess.file_exists(Session.save_path) else PackedByteArray()
	h.check(game.ui.menu.get_children().any(func(child: Node) -> bool: return child is Button and child.text == TextCatalog.text("Boss challenge")), "Title offers a separate boss challenge")
	await h.shot("107_boss_challenge_title")
	game.ui.show_menu("challenge_select")
	await h.shot("108_boss_challenge_select")
	h.check(game.ui.menu.get_children().filter(func(child: Node) -> bool: return child is Button).size() >= 3, "Boss selection offers both chapters and a back action")
	game.ui.challenge_requested.emit(1)
	await h.frames(5)
	h.check(game.room.room_id == "heart_chamber" and game.room.get_node("Enemies/Warden") is HollowWarden and game.player.health.current == game.player.health.maximum, "Chapter I challenge starts the real warden at full health")
	h.check(game.room.get_node("Interactions").get_children().all(func(point: Node) -> bool: return not point.visible), "Challenge hides campaign exits and rewards")
	h.check("double_jump" in Session.abilities and "dash" in Session.abilities and not get_tree().paused, "Challenge grants movement abilities without a campaign save")
	game._on_warden_defeated(game.room.get_instance_id())
	h.check(game.ui.menu_mode == "challenge_complete" and "warden_defeated" not in Session.flags, "Warden challenge victory opens retry choices without a completion flag")
	await h.shot("109_boss_challenge_complete")
	game.ui.challenge_requested.emit(2)
	await h.frames(5)
	h.check(game.room.room_id == "furnace_core" and game.room.get_node("Enemies/FurnaceKeeper") is FurnaceKeeper and "steam_ward" in Session.abilities, "Chapter II challenge starts the real flying keeper with optional shield")
	game.player.health.take_damage(99,game.player.position)
	await h.frames(60)
	h.check(game.room.room_id == "furnace_core" and game.player.health.current == game.player.health.maximum, "Challenge death retries the selected boss at full health")
	game._on_keeper_defeated(game.room.get_instance_id())
	h.check(game.ui.menu_mode == "challenge_complete" and "furnace_keeper_defeated" not in Session.flags, "Keeper challenge victory leaves campaign completion untouched")
	game.ui.title_requested.emit()
	await h.frames(3)
	h.check(not game.running and game.ui.menu_mode == "title" and Session.snapshot() == original, "Returning to the title restores the saved campaign state")
	h.check((FileAccess.get_file_as_bytes(Session.save_path) if FileAccess.file_exists(Session.save_path) else PackedByteArray()) == save_bytes, "Boss challenges do not write the campaign save")
