extends Node
## Real input and collision tests. Positioning isolates mechanics, not a full playthrough.

func action(name: String) -> void:
	var event := InputEventAction.new()
	event.action = name
	event.pressed = true
	Input.parse_input_event(event)

func run(h: Node, game: Node) -> void:
	var player: Player = game.player
	Session.abilities.erase("dash")
	game.load_room("sanctuary","wind_return")
	await h.frames(4)
	await h.press("move_right",15)
	await h.press("interact",2)
	h.check(game.room.room_id == "wind_hall", "Sanctuary route reaches wind ability before its gate")
	await h.frames(5)
	await h.shot("26_wind_entry")
	var start := player.position
	await h.press("dash",11)
	h.check(absf(player.position.x-start.x)<1 and player.state != Player.State.DASH, "Dash unavailable before wind echo")
	player.revive(Vector2(320,480))
	await h.frames(4)
	await h.press("interact",2)
	h.check("dash" in Session.abilities and not game.room.get_node("Interactions/WindEcho").visible, "Wind echo unlocks dash and hides pickup")
	h.check(Session.restore() and "dash" in Session.abilities, "Dash ability survives save restore")
	await h.press("interact",2)
	h.check(Session.abilities.count("dash") == 1, "Wind echo cannot be collected twice")
	player.revive(Vector2(320,480))
	player.facing = 1
	await h.frames(4)
	start = player.position
	Input.action_press("dash")
	await h.frames(4)
	h.check(player.state == Player.State.DASH and not player.attack_box.active, "Dash enters its own harmless movement state")
	await h.shot("27_dash_active")
	await h.frames(7)
	h.check(absf(player.position.x-start.x-111.6)<1 and player.state == Player.State.MOVE, "Dash travels measured 111.6px over 0.18 seconds")
	await h.frames(35)
	h.check(player.state == Player.State.MOVE and player.position.x < start.x+140, "Held dash never repeats after cooldown")
	Input.action_release("dash")
	await h.frames(2)
	player.revive(Vector2(400,480))
	player.facing = -1
	await h.frames(3)
	await h.press("dash",3)
	var remaining := player.dash_left
	action("world_map")
	await h.frames(4)
	start = player.position
	await h.frames(6)
	h.check(player.position == start and player.dash_left == remaining, "Map freezes an active dash and its timer")
	action("world_map")
	await h.frames(12)
	h.check(player.state == Player.State.MOVE and player.position.x < 310, "Dash resumes facing left after closing map")
	player.revive(Vector2(400,480))
	await h.frames(3)
	action("pause")
	await h.frames(2)
	Input.action_press("dash")
	game.resume()
	await h.frames(6)
	h.check(player.state == Player.State.MOVE and absf(player.position.x-400)<1, "Held dash during pause is ignored on resume")
	Input.action_release("dash")
	await h.frames(2)
	player.revive(Vector2(450,480))
	player.facing = -1
	await h.frames(3)
	await h.press("dash",12)
	await h.press("dash",2)
	h.check(player.state != Player.State.DASH and player.dash_cooldown_left > 0, "Cooldown rejects an immediate second dash")
	# High starting point gives enough airborne time to outlast cooldown.
	player.revive(Vector2(350,80))
	player.facing = 1
	await h.frames(2)
	await h.press("dash",12)
	await h.frames(17)
	await h.press("dash",2)
	h.check(not player.is_on_floor() and player.air_dash_used and player.state != Player.State.DASH, "Air dash cannot repeat even after cooldown")
	await h.frames(35)
	h.check(player.is_on_floor() and not player.air_dash_used, "Landing replenishes the airborne dash")
	# Dash consumes neither the second jump nor grants another air dash after it.
	player.revive(Vector2(350,480))
	player.facing = 1
	await h.frames(3)
	await h.press("jump",14)
	await h.press("dash",12)
	Input.action_press("jump")
	await h.frames(2)
	h.check(player.air_jump_used and player.velocity.y < -400 and player.air_dash_used, "Double jump still works after dash without replenishing air dash")
	Input.action_release("jump")
	await h.frames(60)
	player.revive(Vector2(400,480))
	await h.frames(3)
	Input.action_press("attack")
	await h.frames(2)
	await h.press("dash",2)
	h.check(player.state == Player.State.ATTACK, "Dash does not cancel sword commitment")
	Input.action_release("attack")
	await h.frames(25)
	player.revive(Vector2(400,480))
	await h.frames(3)
	await h.press("dash",2)
	var hp := player.health.current
	player.health.take_damage(1,player.position+Vector2(20,0))
	h.check(player.state == Player.State.HURT and player.dash_left == 0 and player.health.current == hp-1, "Dash grants no invulnerability and damage interrupts it")
	# A 2px wall checks swept CharacterBody collision at dash speed.
	player.revive(Vector2(400,480))
	player.facing = 1
	var wall := StaticBody2D.new()
	wall.position = Vector2(450,450)
	var shape := CollisionShape2D.new()
	var rect := RectangleShape2D.new()
	rect.size = Vector2(2,100)
	shape.shape = rect
	wall.add_child(shape)
	game.room.add_child(wall)
	await h.frames(3)
	await h.press("dash",11)
	h.check(player.position.x < 440 and player.state != Player.State.DASH, "Dash cannot tunnel through a two-pixel normal wall")
	wall.queue_free()
	await h.frames(3)
	var gate := game.room.get_node("Gates/WindGate") as WindGate
	player.revive(Vector2(570,120))
	await h.frames(3)
	await h.press("move_right",12)
	h.check(player.position.x < 590 and not gate.opened, "High airborne movement cannot bypass the full-height wind barrier")
	player.revive(Vector2(545,480))
	await h.frames(3)
	await h.press("move_right",25)
	h.check(player.position.x < 590 and not gate.opened, "Walking cannot cross or open the wind barrier")
	await h.press("attack",24)
	h.check(not gate.opened, "Sword attacks cannot open the wind barrier")
	await h.shot("28_wind_barrier")
	await h.press("dash",12)
	h.check(gate.opened and player.position.x > 620 and "wind_passage_open" in Session.flags, "Actual dash collision opens and crosses the wind barrier")
	h.check(Session.restore() and "wind_passage_open" in Session.flags, "Wind barrier opening is persisted")
	await h.shot("29_wind_open")
	await h.press("move_right",44)
	await h.press("interact",2)
	h.check(game.room.room_id == "belfry", "Opened passage leads to the silent belfry")
	await h.frames(5)
	await h.shot("30_belfry_entry")
	h.check(game.room.get_node("Enemies").get_child_count() == 2, "Belfry combines established melee and ranged enemies")
	player.revive(Vector2(165,480))
	await h.frames(3)
	await h.press("interact",2)
	h.check(Session.checkpoint_room == "belfry", "Belfry checkpoint saves its stable room ID")
	await h.frames(30)
	h.check(player.health.current == player.health.maximum and game.room.projectiles.get_child_count() == 0, "Belfry checkpoint stays safe from both encounters")
	player.revive(Vector2(275,480))
	await h.frames(3)
	Input.action_press("jump")
	Input.action_press("move_right")
	await h.frames(23)
	Input.action_release("move_right")
	Input.action_release("jump")
	await h.frames(25)
	h.check(player.is_on_floor() and absf(player.position.y-416)<2, "Belfry first cover is reachable with a normal jump")
	player.revive(Vector2(1140,480))
	player.health.invulnerability_left = 30
	await h.frames(3)
	await h.press("interact",2)
	h.check("belfry_cleared" not in Session.flags, "Living enemies prevent lighting the wind beacon")
	# Existing combat suites verify attacks; here use real sword strikes with damage isolation.
	for enemy: Node in game.room.get_node("Enemies").get_children():
		for attempt: int in range(8):
			if not is_instance_valid(enemy) or enemy.health.current <= 0:
				break
			player.revive(enemy.position-Vector2(45,0))
			player.facing = 1
			player.health.invulnerability_left = 30
			await h.frames(2)
			await h.press("attack",24)
	await h.frames(40)
	h.check(game.room.is_cleared(), "Sword combat clears the new belfry encounter")
	player.revive(Vector2(1140,480))
	await h.frames(3)
	await h.press("interact",2)
	h.check("belfry_cleared" in Session.flags, "Wind beacon unlocks its permanent shortcut")
	h.check(Session.restore() and "belfry_cleared" in Session.flags, "Belfry beacon and shortcut survive save restore")
	await h.shot("31_belfry_beacon")
	player.revive(Vector2(1230,480))
	await h.frames(3)
	await h.press("interact",2)
	h.check(game.room.room_id == "forest" and absf(player.position.y-224)<2, "Belfry shortcut returns safely to the high grove")
	game.load_room("wind_hall","east")
	await h.frames(3)
	h.check(game.room.get_node("Gates/WindGate").opened, "Revisiting wind gallery restores its open barrier")
	# Walk back through the same gate; no one-way trap or forced repeat dash.
	player.revive(Vector2(650,480))
	await h.frames(3)
	await h.press("move_left",36)
	h.check(player.position.x < 550, "Opened wind barrier remains walkable in the return direction")
	player.revive(Vector2(48,480))
	await h.frames(3)
	await h.press("interact",2)
	h.check(game.room.room_id == "sanctuary" and absf(player.position.x-805)<2, "Wind gallery west exit returns to a safe sanctuary spawn")
	game.load_room("wind_hall","entry")
	player.revive(Vector2(400,480))
	await h.frames(3)
	await h.press("dash",2)
	game.load_room("belfry","checkpoint")
	h.check(player.state != Player.State.DASH and player.dash_left == 0, "Room change cancels active dash")
	await h.frames(3)
	player.revive(Vector2(165,480))
	await h.frames(3)
	await h.press("dash",2)
	player.health.take_damage(99,player.position)
	h.check(player.state == Player.State.DEAD and player.dash_left == 0, "Death cancels dash immediately")
	await h.frames(65)
	h.check(game.room.room_id == "belfry" and player.health.current == 6 and "dash" in Session.abilities, "Death restores belfry checkpoint with both permanent upgrades")
	action("world_map")
	await h.frames(3)
	h.check(game.ui.world_map.room_label("belfry") == "SILENT BELFRY", "Map reveals the new explored route")
	await h.shot("32_wind_map")
	action("world_map")
	await h.frames(2)
