extends Node
## Actual traversal and UI input; isolation snapshots keep prior suites independent.

func event(action: String) -> void:
	var input := InputEventAction.new()
	input.action = action
	input.pressed = true
	Input.parse_input_event(input)

func run(h: Node, game: Node) -> void:
	var player: Player = game.player
	var visited := Session.visited.duplicate()
	var abilities := Session.abilities.duplicate()
	Session.visited.assign(["forest"])
	Session.abilities.clear()
	game.load_room("forest","entry")
	player.revive(Vector2(175,480))
	await h.frames(4)
	event("world_map")
	await h.frames(3)
	var map: WorldMap = game.ui.world_map
	h.check(get_tree().paused and game.ui.map_panel.visible, "Map action opens a paused room map")
	h.check(map.current_room == "forest" and map.room_label("forest") == "FORGOTTEN GROVE", "Map marks current explored room")
	h.check(map.revealed("ruins") and map.room_label("ruins") == "UNEXPLORED", "Adjacent unexplored room does not reveal its name")
	h.check(not map.revealed("sanctuary") and not map.revealed("scriptorium"), "Map hides secret and distant rooms before discovery")
	var close := game.ui.map_panel.find_child("CloseMap",true,false) as Button
	h.check(close.has_focus(), "Map provides keyboard and controller focus on return")
	var at := player.position
	Input.action_press("attack")
	Input.action_press("jump")
	await h.frames(5)
	h.check(player.position == at, "Map freezes player physics")
	await h.shot("20_map_discovery")
	close.pressed.emit()
	await h.frames(3)
	h.check(not get_tree().paused and not game.ui.map_panel.visible and player.state == Player.State.MOVE and player.is_on_floor(), "Map return ignores held jump and attack")
	Input.action_release("attack")
	Input.action_release("jump")
	await h.frames(3)
	event("pause")
	await h.frames(2)
	event("world_map")
	await h.frames(2)
	event("pause")
	await h.frames(2)
	h.check(get_tree().paused and game.ui.modal.visible and game.ui.menu_mode == "pause" and not game.ui.map_panel.visible, "Closing map over pause restores the pause menu")
	game.resume()
	# Gate cannot be bypassed by interaction radius or missing ability.
	player.revive(Vector2(490,224))
	await h.frames(3)
	await h.press("interact",2)
	h.check(game.room.room_id == "forest", "Secret door rejects entry without double jump")
	Session.abilities.assign(abilities)
	Session.visited.assign(visited)
	Session.progress_changed.emit()
	# Existing low/high platforms lead to the actual new door without teleporting up.
	player.revive(Vector2(305,384))
	await h.frames(4)
	Input.action_press("jump")
	await h.frames(18)
	Input.action_release("jump")
	await h.frames(1)
	Input.action_press("jump")
	Input.action_press("move_right")
	await h.frames(23)
	Input.action_release("move_right")
	Input.action_release("jump")
	await h.frames(30)
	h.check(player.is_on_floor() and absf(player.position.y-224)<2, "Double jump physically reaches secret branch height")
	await h.press("move_right",24)
	await h.shot("24_high_roots")
	await h.press("interact",2)
	h.check(game.room.room_id == "sanctuary", "High grove door enters the sanctuary after real traversal")
	await h.frames(5)
	await h.shot("21_sanctuary_entry")
	player.revive(Vector2(165,480))
	await h.frames(3)
	await h.press("interact",2)
	h.check(Session.checkpoint_room == "sanctuary", "Sanctuary checkpoint saves the new room")
	# Native platforms rise 64px with 64px gaps. Move to each takeoff on foot.
	player.revive(Vector2(205,480))
	await h.frames(4)
	for step: int in range(3):
		Input.action_press("move_right")
		Input.action_press("jump")
		await h.frames(31)
		Input.action_release("move_right")
		Input.action_release("jump")
		await h.frames(23)
		h.check(player.is_on_floor() and absf(player.position.y-(416-step*64))<2, "Sanctuary step %d is reachable using actual jump input" % (step+1))
		if step < 2:
			await h.press("move_right",19)
	await h.shot("25_heart_bloom_waiting")
	await h.press("interact",2)
	h.check("heart_bloom" in Session.flags and player.health.maximum == 6 and player.health.current == 6, "Heart bloom grants and heals one permanent maximum HP")
	h.check(not game.room.get_node("Interactions/HeartBloom").visible, "Claimed heart bloom is hidden")
	await h.shot("22_heart_bloom")
	await h.press("interact",2)
	h.check(player.health.maximum == 6 and Session.flags.count("heart_bloom") == 1, "Repeated interaction cannot stack the health reward")
	h.check(Session.restore() and Session.maximum_health() == 6 and "sanctuary" in Session.visited, "Save restore retains reward and explored sanctuary")
	var fresh := preload("res://features/player/player.tscn").instantiate() as Player
	fresh.position = Vector2(850,480)
	game.add_child(fresh)
	h.check(fresh.health.maximum == 6 and fresh.health.current == 6, "Fresh player instance receives saved health capacity")
	fresh.queue_free()
	player.health.take_damage(99,player.position)
	await h.frames(65)
	h.check(game.room.room_id == "sanctuary" and absf(player.position.x-165)<2 and player.health.current == 6, "Death preserves upgraded vitality at sanctuary checkpoint")
	h.check(not game.room.get_node("Interactions/HeartBloom").visible, "Room reload preserves unique reward state")
	event("world_map")
	await h.frames(3)
	h.check(map.current_room == "sanctuary" and map.checkpoint_room == "sanctuary" and map.room_label("sanctuary") == "ROOT SANCTUARY", "Map updates visited name current location and checkpoint")
	await h.shot("23_map_explored")
	event("world_map")
	await h.frames(2)
	player.revive(Vector2(48,480))
	await h.frames(3)
	await h.press("interact",2)
	h.check(game.room.room_id == "forest" and absf(player.position.y-224)<2, "Sanctuary return places player safely on the high forest ledge")
	# Completed overlay must survive a map round trip too.
	get_tree().paused = true
	game.ui.show_menu("win")
	event("world_map")
	await h.frames(2)
	event("world_map")
	await h.frames(2)
	h.check(get_tree().paused and game.ui.menu_mode == "win", "Map restores the completion overlay when opened above it")
	game.resume()
	await h.frames(3)
