class_name TextCatalog
extends RefCounted
## Source English strings are stable translation keys; native Godot Translation backend.
const ZH := {
	"10 / EMBER QUAY": "10 / 余烬渡口",
	"11 / VALVE GALLERY": "11 / 阀门长廊",
	"12 / CISTERN ARCHIVE": "12 / 水道档案室",
	"13 / FURNACE CORE": "13 / 炉心",
	"EMBER QUAY": "余烬渡口",
	"VALVE GALLERY": "阀门长廊",
	"CISTERN ARCHIVE": "水道档案室",
	"FURNACE CORE": "炉心",
	"E / CHAPTER II - EMBER CISTERN": "E / 第二关 · 余烬水道",
	"E / RETURN TO THE HEART CHAMBER": "E / 返回空谷心室",
	"E / ENTER THE VALVE GALLERY": "E / 进入阀门长廊",
	"E / ENTER THE CISTERN ARCHIVE": "E / 进入水道档案室",
	"E / ENTER THE FURNACE CORE": "E / 进入炉心",
	"E / RETURN TO EMBER QUAY": "E / 返回余烬渡口",
	"E / CLAIM THE FLOW SEAL": "E / 获取流量阀印",
	"E / CLAIM THE PRESSURE SEAL": "E / 获取压力阀印",
	"E / RESTORE THE CISTERN CORE": "E / 唤醒水道炉心",
	"Steam: amber warns, white burns. Cross on green.": "蒸汽：琥珀预警、白色喷发；绿色停歇时通过。",
	"Two branches, two valve seals. Return here to open the core.": "探索两条支路，收集两枚阀印，再回来开启炉心。",
	"Climb the dry ledges. Wait for the steam to settle.": "沿干燥台阶向上，等待蒸汽停歇再前进。",
	"Winged chest: jump the bite, strike after it lands.": "飞翼宝箱蓄力后扑咬：跳过扑击，落地后反击。",
	"Dry stone blocks ink. Fight away from the steam.": "石台可以挡住墨弹，远离喷口再交战。",
	"Draw guardians onto dry ground. Restore the core after battle.": "把敌人引向干燥地面，清场后唤醒炉心。",
	"Missing flow seal / Explore Valve Gallery": "缺少流量阀印 / 探索阀门长廊",
	"Missing pressure seal / Explore Cistern Archive": "缺少压力阀印 / 探索水道档案室",
	"Restore the final echo before entering Chapter II": "先唤醒最终回响，再进入第二关。",
	"Chapter II / Beyond the heart chamber": "第二关 / 穿过空谷心室右侧的门",
	"Claim the flow seal / Valve Gallery": "取得流量阀印 / 阀门长廊",
	"Claim the pressure seal / Cistern Archive": "取得压力阀印 / 水道档案室",
	"Two valves ready / Enter the furnace core": "双阀已就绪 / 前往渡口东侧炉心门",
	"Cistern restored / Both chapters open to explore": "水道已复苏 / 两章均可自由探索",
	"FLOW SEAL ACQUIRED": "已获得 · 流量阀印",
	"PRESSURE SEAL ACQUIRED": "已获得 · 压力阀印",
	"One of two furnace valves restored": "已修复一枚炉心阀印，共需两枚",
	"All vitality restored. Return to Ember Quay.": "生命已全部恢复，请返回余烬渡口。",
	"CISTERN RESTORED": "余烬水道复苏",
	"Steam vents are now safe throughout Chapter II": "第二关所有蒸汽喷口已永久停用",
	"Both chapters remain open to explore.": "可返回两章区域继续探索。",
	"Flow seal": "流量阀印",
	"Pressure seal": "压力阀印",
	"Cistern core": "水道炉心",
	"Final echo": "最终回响",
	"Two valve seals": "两枚阀印",
	"Chapter II / Show Chapter I": "第二关地图 / 切换到第一关",
	"Chapter I / Show Chapter II": "第一关地图 / 切换到第二关",
	"Settings": "设置",
	"Back": "返回",
	"Settings saved": "设置已保存",
	"Music volume": "音乐音量",
	"Sound volume": "音效音量",
	"Fullscreen": "全屏显示",
	"Move left": "向左移动",
	"Move": "移动",
	"Move right": "向右移动",
	"Jump": "跳跃",
	"Attack": "攻击",
	"Dash": "冲刺",
	"Interact": "交互",
	"Map": "地图",
	"Pause": "暂停",
	"Mute": "静音",
	"Reset bindings": "恢复默认按键",
	"Select an action, then press a key or gamepad button. ESC cancels.": "选择动作后，按下键盘按键或手柄按钮。ESC 取消；暂停键保留。",
	"Waiting for input / ESC to cancel": "等待输入 / ESC 或 Start 取消",
	"Binding cancelled": "已取消修改按键",
	"Use a single key without modifiers": "请使用单个按键，不要组合功能键",
	"Reserved for menu navigation": "该按键保留用于菜单导航",
	"Already assigned: ": "该按键已用于：",
	"Unsupported input": "不支持此输入",
	"Press a keyboard key or gamepad button": "请按键盘按键或手柄按钮",
	"Start a new journey?": "开始新旅程？",
	"Dash locked": "冲刺未解锁",
	"Dash ready": "冲刺就绪",
	"Dashing": "冲刺中",
	"Dash unavailable": "冲刺暂不可用",
	"Dash recharging": "冲刺恢复中",
	"Dash: land to recharge": "冲刺：落地恢复",
	"Warden awakens": "守门者苏醒",
	"Phase II / Faster pursuit": "第二阶段 / 追击加速",
	"RUSH / Jump over": "突进 / 起跳躲避",
	"SWEEP / Step back or behind": "横扫 / 退开或绕后",
	"RECOVERY / Strike now": "收招 / 趁机反击",
	"Watchers seal": "守望者封印",
	"Ink seal": "墨文封印",
	"Wind beacon": "风信标",
	"Double jump": "二段跳",
	"Wind dash": "风之冲刺",
	"Three marks": "三枚印记",
	"NEXT": "目标",
	"Locked: ": "锁门条件：",
	"Hollow restored / Explore the paths you opened": "空谷已复苏 / 继续探索已开启的道路",
	"Warden defeated / Restore the final echo": "守门者已倒下 / 唤醒最终回响",
	"Antechamber reached / Face the Hollow Warden": "已抵达回响前庭 / 挑战空谷守门者",
	"HEART CHAMBER": "空谷心室",
	"09 / HEART CHAMBER": "09 / 空谷心室",
	"E / FACE THE HOLLOW WARDEN": "E / 挑战空谷守门者",
	"E / RETURN TO THE ANTECHAMBER": "E / 返回回响前庭",
	"Amber: step away. Mint: jump the rush. Strike after.": "琥珀预警先退开，青绿突进跳过，收招时反击。",
	"E / RESTORE THE FINAL ECHO": "E / 唤醒最终回响",
	"HOLLOW WARDEN / I": "空谷守门者 / 第一阶段",
	"HOLLOW WARDEN / II": "空谷守门者 / 第二阶段",
	"HOLLOW WARDEN DEFEATED": "已击败 · 空谷守门者",
	"The final echo is now within reach": "最终回响已解封",
	"All vitality restored. Claim the echo on your right.": "生命已全部恢复，前往右侧唤醒最终回响。",
	"HOLLOW RESTORED": "空谷复苏",
	"The warden rests. The grove remembers your journey.": "守门者归于宁静，林地将铭记你的旅程。",
	"Find the sky echo / Eastern archive": "前往东侧档案馆，寻找天空回响",
	"Claim the Watchers seal / East of the archive": "前往档案馆东侧，取得守望者封印",
	"Claim the Ink seal / Through Watchers Hall": "穿过守望者训练厅，取得墨文封印",
	"Find the wind echo / Above the grove": "沿林地高处树根前进，寻找风之回响",
	"Light the wind beacon / Beyond Wind Gallery": "穿过风廊，在钟楼点亮风信标",
	"Three marks gathered / Grove ground-level gate": "三印已齐 / 前往林地地面三印门",
	"Antechamber reached / Rest before the sealed door": "已抵达回响前庭 / 在封闭内门前休整",
	"The grove remembers. Seek the three marks.": "林地回响已唤醒，请继续寻找三枚印记。",
	"ECHO ANTECHAMBER": "回响前庭",
	"08 / ECHO ANTECHAMBER": "08 / 回响前庭",
	"E / THREE-MARK GATE": "E / 三印门 · 通往回响前庭",
	"Missing Watchers seal / Hall east of the archive": "缺少守望者封印 / 前往档案馆东侧训练厅",
	"Missing Ink seal / Entrance inside Watchers Hall": "缺少墨文封印 / 入口位于守望者训练厅内",
	"Missing wind beacon / Belfry beyond Wind Gallery": "尚未点亮风信标 / 穿过风廊前往钟楼",
	"A quiet threshold. Rest here before going onward.": "这里没有敌人。前行之前，请在祭坛休息并保存。",
	"Inner door sealed / The guardian awakens in a future chapter.": "内门尚未开启 / 守门者将在后续篇章登场。",
	"ECHOES OF THE HOLLOW": "空谷回响",
	"ECHO RESTORED": "回响已唤醒",
	"PAUSED": "已暂停",
	"A small journey through the forgotten grove": "穿行遗忘林地，寻回失落的回响",
	"Continue from checkpoint": "从存档点继续",
	"New journey": "开始新旅程",
	"New journey replaces progress on the next save.": "新旅程会在下次保存时覆盖原进度。",
	"Continue exploring": "继续探索",
	"Resume": "继续游戏",
	"Quit": "退出游戏",
	"Reduce screen shake": "减弱屏幕震动",
	"Reduce hit flashes": "减弱受击闪烁",
	"Settings could not be saved": "设置保存失败，请稍后重试",
	"VITALITY": "生命",
	"Find the echo in the eastern ruins": "前往东侧遗迹，寻找回响",
	"Wind route open / Explore freely": "风之通路已开启 / 自由探索",
	"Dash through the wind / Reach the silent belfry": "冲破风障，前往寂静钟楼",
	"Echo restored / Explore freely": "回响已唤醒 / 自由探索",
	"Double jump unlocked / Return to the high shrine": "已解锁二段跳 / 返回高台祭坛",
	"A/D Move  SPACE Jump  J Attack  K Dash  E Use  Q Map  ESC Pause  M Mute": "A/D 移动  空格 跳跃  J 攻击  K 冲刺  E 交互  Q 地图  ESC 暂停  M 静音",
	"PATHS OF THE HOLLOW": "空谷地图",
	"Return / Q or ESC": "返回 / Q 或 ESC",
	"UNEXPLORED": "尚未探索",
	"HERE": "当前",
	"VISITED": "已探索",
	"SAVE": "存档",
	"+HP": "+生命",
	"ROOT SANCTUARY": "树根秘境",
	"WIND GALLERY": "风廊",
	"SILENT BELFRY": "寂静钟楼",
	"FORGOTTEN GROVE": "遗忘林地",
	"THE ARCHIVE": "沉没档案馆",
	"WATCHERS HALL": "守望者训练厅",
	"INK SANCTUM": "墨文圣所",
	"01 / THE FORGOTTEN GROVE": "01 / 遗忘林地",
	"02 / THE SUNKEN ARCHIVE": "02 / 沉没档案馆",
	"03 / THE WATCHERS HALL": "03 / 守望者训练厅",
	"04 / THE INK SANCTUM": "04 / 墨文圣所",
	"05 / ROOT SANCTUARY": "05 / 树根秘境",
	"06 / WIND GALLERY": "06 / 风廊",
	"07 / SILENT BELFRY": "07 / 寂静钟楼",
	"E  /  REST & SAVE": "E / 休息并保存",
	"E / REST & SAVE": "E / 休息并保存",
	"E / RECOVER & SAVE": "E / 恢复生命并保存",
	"E  /  RETURN TO THE GROVE": "E / 返回林地",
	"E / RETURN TO THE GROVE": "E / 返回林地",
	"E  /  CLAIM THE SKY ECHO": "E / 获取天空回响",
	"E / ENTER THE WATCHERS HALL": "E / 进入守望者训练厅",
	"E  /  ENTER THE ARCHIVE": "E / 进入档案馆",
	"E  /  RESTORE THE HOLLOW": "E / 唤醒空谷回响",
	"E / FOLLOW THE HIGH ROOTS": "E / 沿高处树根前进",
	"E / RETURN TO WATCHERS HALL": "E / 返回守望者训练厅",
	"Violet charge: jump the bolt. Cover blocks ink.": "看到紫色蓄力时跳跃躲弹，掩体能挡住墨弹。",
	"E / CLAIM THE INK SEAL": "E / 获取墨文封印",
	"E / RETURN TO THE ARCHIVE": "E / 返回档案馆",
	"Watch the amber warning. Step back, then strike.": "留意琥珀色预警：先后退，再反击。",
	"E / CLAIM THE HALL SEAL": "E / 获取守望者封印",
	"E / FOREST SHORTCUT": "E / 使用林地捷径",
	"E / ENTER THE INK SANCTUM": "E / 进入墨文圣所",
	"E / RETURN TO WIND GALLERY": "E / 返回风廊",
	"Dash to reposition. Strike after the warning.": "用冲刺调整位置，等敌人出招后再反击。",
	"E / LIGHT THE WIND BEACON": "E / 点亮风信标",
	"E / RETURN TO THE ROOTS": "E / 返回树根秘境",
	"E / CLAIM THE WIND ECHO": "E / 获取风之回响",
	"K: dash through wind. No invincibility.": "按 K 冲破风障。冲刺不提供无敌。",
	"E / ENTER THE SILENT BELFRY": "E / 进入寂静钟楼",
	"E / RETURN TO THE HIGH GROVE": "E / 返回林地高台",
	"Above the roots, a heart still blooms.": "树根之上，生命之花仍在绽放。",
	"E / CLAIM HEART BLOOM / +1 MAX VITALITY": "E / 获取生命之花 / 生命上限 +1",
	"E / FOLLOW THE WIND": "E / 循风前进",
	"Save unavailable. Starting a new journey.": "存档不可用，已开始新旅程。",
	"The high roots answer only to the sky echo": "先取得天空回响，才能沿高处树根前进。",
	"Clear this hall and claim its seal first": "请先清理此区域并领取封印。",
	"Restored & saved": "生命已恢复，进度已保存。",
	"Defeat the hall guardians to release the seal": "击败此区域的所有敌人，才能领取奖励。",
	"The shrine awaits an echo from the eastern ruins": "祭坛等待来自东侧遗迹的回响。",
	"The grove remembers. Journey complete.": "林地回响已唤醒，可以继续探索。",
	"Save failed / Progress remains in this session": "保存失败 / 进度暂保留在本次游戏中",
	"Wind barrier opened / Route saved": "风障已开启 / 通路进度已保存",
	"Returning to the last shrine...": "正在返回最近的存档点……",
	"SKY ECHO ACQUIRED": "已获得 · 天空回响",
	"Double jump unlocked": "解锁二段跳",
	"Press SPACE again in the air.": "在空中再次按空格，即可二段跳。",
	"WIND ECHO ACQUIRED": "已获得 · 风之回响",
	"Wind dash unlocked": "解锁风之冲刺",
	"K / Right shoulder to dash. No invincibility.": "按 K / 手柄右肩冲刺；冲刺没有无敌。",
	"HEART BLOOM ACQUIRED": "已获得 · 生命之花",
	"Maximum vitality +1 permanently": "生命上限永久 +1",
	"All vitality restored.": "生命已全部恢复。",
	"WATCHERS SEAL ACQUIRED": "已获得 · 守望者封印",
	"Forest shortcut + Ink Sanctum entrance unlocked": "解锁林地捷径与墨文圣所入口",
	"All vitality restored. Take the east exit to the grove.": "生命已全部恢复，从右侧出口返回林地。",
	"INK SEAL ACQUIRED": "已获得 · 墨文封印",
	"Archive return route unlocked": "解锁返回档案馆的通路",
	"All vitality restored. Take the east exit.": "生命已全部恢复，请使用右侧出口。",
	"WIND BEACON LIT": "已点亮 · 风信标",
	"Shortcut to the high grove unlocked": "解锁返回森林高台的捷径",
	"All vitality restored. Take the door on your right.": "生命已全部恢复，从右侧的门即可返回。",
	"Progress saved": "进度已保存",
	"Save failed - visit a shrine to retry": "保存失败，请到存档点重新保存"
}

static func install() -> void:
	var translation := Translation.new()
	translation.locale = "zh_CN"
	for key: String in ZH:
		translation.add_message(key,ZH[key])
	TranslationServer.add_translation(translation)

static var input_formatter: Callable

static func text(source: String) -> String:
	var translated := String(TranslationServer.translate(source))
	return input_formatter.call(source, translated) if input_formatter.is_valid() else translated
