class_name TextCatalog
extends RefCounted
## Source English strings are stable translation keys; native Godot Translation backend.
const ZH := {
	"Hollow restored / Explore the paths you opened": "空谷已复苏 / 继续探索已开启的道路",
	"Warden defeated / Restore the final echo": "守门者已倒下 / 唤醒最终回响",
	"Antechamber reached / Face the Hollow Warden": "已抵达回响前庭 / 挑战空谷守门者",
	"HEART CHAMBER": "空谷心室",
	"09 / HEART CHAMBER": "09 / 空谷心室",
	"E / FACE THE HOLLOW WARDEN": "E / 挑战空谷守门者",
	"E / RETURN TO THE ANTECHAMBER": "E / 返回回响前庭",
	"Amber: step away. Mint: jump the rush. Strike after.": "琥珀预警先退开，青绿突进跳过，收招时反击。",
	"E / RESTORE THE FINAL ECHO": "E / 唤醒最终回响",
	"HOLLOW WARDEN / I": "空谷守门者 / 第一阶段",
	"HOLLOW WARDEN / II": "空谷守门者 / 第二阶段",
	"HOLLOW WARDEN DEFEATED": "已击败 · 空谷守门者",
	"The final echo is now within reach": "最终回响已解封",
	"All vitality restored. Claim the echo on your right.": "生命已全部恢复，前往右侧唤醒最终回响。",
	"HOLLOW RESTORED": "空谷复苏",
	"The warden rests. The grove remembers your journey.": "守门者归于宁静，林地将铭记你的旅程。",
	"Find the sky echo / Eastern archive": "前往东侧档案馆，寻找天空回响",
	"Claim the Watchers seal / East of the archive": "前往档案馆东侧，取得守望者封印",
	"Claim the Ink seal / Through Watchers Hall": "穿过守望者训练厅，取得墨文封印",
	"Find the wind echo / Above the grove": "沿林地高处树根前进，寻找风之回响",
	"Light the wind beacon / Beyond Wind Gallery": "穿过风廊，在钟楼点亮风信标",
	"Three marks gathered / Grove ground-level gate": "三印已齐 / 前往林地地面三印门",
	"Antechamber reached / Rest before the sealed door": "已抵达回响前庭 / 在封闭内门前休整",
	"The grove remembers. Seek the three marks.": "林地回响已唤醒，请继续寻找三枚印记。",
	"ECHO ANTECHAMBER": "回响前庭",
	"08 / ECHO ANTECHAMBER": "08 / 回响前庭",
	"E / THREE-MARK GATE": "E / 三印门 · 通往回响前庭",
	"Missing Watchers seal / Hall east of the archive": "缺少守望者封印 / 前往档案馆东侧训练厅",
	"Missing Ink seal / Entrance inside Watchers Hall": "缺少墨文封印 / 入口位于守望者训练厅内",
	"Missing wind beacon / Belfry beyond Wind Gallery": "尚未点亮风信标 / 穿过风廊前往钟楼",
	"A quiet threshold. Rest here before going onward.": "这里没有敌人。前行之前，请在祭坛休息并保存。",
	"Inner door sealed / The guardian awakens in a future chapter.": "内门尚未开启 / 守门者将在后续篇章登场。",
	"ECHOES OF THE HOLLOW": "空谷回响",
	"ECHO RESTORED": "回响已唤醒",
	"PAUSED": "已暂停",
	"A small journey through the forgotten grove": "穿行遗忘林地，寻回失落的回响",
	"Continue from checkpoint": "从存档点继续",
	"New journey": "开始新旅程",
	"New journey replaces progress on the next save.": "新旅程会在下次保存时覆盖原进度。",
	"Continue exploring": "继续探索",
	"Resume": "继续游戏",
	"Quit": "退出游戏",
	"Reduce screen shake": "减弱屏幕震动",
	"Reduce hit flashes": "减弱受击闪烁",
	"Settings could not be saved": "设置保存失败，请稍后重试",
	"VITALITY": "生命",
	"Find the echo in the eastern ruins": "前往东侧遗迹，寻找回响",
	"Wind route open / Explore freely": "风之通路已开启 / 自由探索",
	"Dash through the wind / Reach the silent belfry": "冲破风障，前往寂静钟楼",
	"Echo restored / Explore freely": "回响已唤醒 / 自由探索",
	"Double jump unlocked / Return to the high shrine": "已解锁二段跳 / 返回高台祭坛",
	"A/D Move  SPACE Jump  J Attack  K Dash  E Use  Q Map  ESC Pause  M Mute": "A/D 移动  空格 跳跃  J 攻击  K 冲刺  E 交互  Q 地图  ESC 暂停  M 静音",
	"PATHS OF THE HOLLOW": "空谷地图",
	"Return / Q or ESC": "返回 / Q 或 ESC",
	"UNEXPLORED": "尚未探索",
	"HERE": "当前",
	"VISITED": "已探索",
	"SAVE": "存档",
	"+HP": "+生命",
	"ROOT SANCTUARY": "树根秘境",
	"WIND GALLERY": "风廊",
	"SILENT BELFRY": "寂静钟楼",
	"FORGOTTEN GROVE": "遗忘林地",
	"THE ARCHIVE": "沉没档案馆",
	"WATCHERS HALL": "守望者训练厅",
	"INK SANCTUM": "墨文圣所",
	"01 / THE FORGOTTEN GROVE": "01 / 遗忘林地",
	"02 / THE SUNKEN ARCHIVE": "02 / 沉没档案馆",
	"03 / THE WATCHERS HALL": "03 / 守望者训练厅",
	"04 / THE INK SANCTUM": "04 / 墨文圣所",
	"05 / ROOT SANCTUARY": "05 / 树根秘境",
	"06 / WIND GALLERY": "06 / 风廊",
	"07 / SILENT BELFRY": "07 / 寂静钟楼",
	"E  /  REST & SAVE": "E / 休息并保存",
	"E / REST & SAVE": "E / 休息并保存",
	"E / RECOVER & SAVE": "E / 恢复生命并保存",
	"E  /  RETURN TO THE GROVE": "E / 返回林地",
	"E / RETURN TO THE GROVE": "E / 返回林地",
	"E  /  CLAIM THE SKY ECHO": "E / 获取天空回响",
	"E / ENTER THE WATCHERS HALL": "E / 进入守望者训练厅",
	"E  /  ENTER THE ARCHIVE": "E / 进入档案馆",
	"E  /  RESTORE THE HOLLOW": "E / 唤醒空谷回响",
	"E / FOLLOW THE HIGH ROOTS": "E / 沿高处树根前进",
	"E / RETURN TO WATCHERS HALL": "E / 返回守望者训练厅",
	"Violet charge: jump the bolt. Cover blocks ink.": "看到紫色蓄力时跳跃躲弹，掩体能挡住墨弹。",
	"E / CLAIM THE INK SEAL": "E / 获取墨文封印",
	"E / RETURN TO THE ARCHIVE": "E / 返回档案馆",
	"Watch the amber warning. Step back, then strike.": "留意琥珀色预警：先后退，再反击。",
	"E / CLAIM THE HALL SEAL": "E / 获取守望者封印",
	"E / FOREST SHORTCUT": "E / 使用林地捷径",
	"E / ENTER THE INK SANCTUM": "E / 进入墨文圣所",
	"E / RETURN TO WIND GALLERY": "E / 返回风廊",
	"Dash to reposition. Strike after the warning.": "用冲刺调整位置，等敌人出招后再反击。",
	"E / LIGHT THE WIND BEACON": "E / 点亮风信标",
	"E / RETURN TO THE ROOTS": "E / 返回树根秘境",
	"E / CLAIM THE WIND ECHO": "E / 获取风之回响",
	"K: dash through wind. No invincibility.": "按 K 冲破风障。冲刺不提供无敌。",
	"E / ENTER THE SILENT BELFRY": "E / 进入寂静钟楼",
	"E / RETURN TO THE HIGH GROVE": "E / 返回林地高台",
	"Above the roots, a heart still blooms.": "树根之上，生命之花仍在绽放。",
	"E / CLAIM HEART BLOOM / +1 MAX VITALITY": "E / 获取生命之花 / 生命上限 +1",
	"E / FOLLOW THE WIND": "E / 循风前进",
	"Save unavailable. Starting a new journey.": "存档不可用，已开始新旅程。",
	"The high roots answer only to the sky echo": "先取得天空回响，才能沿高处树根前进。",
	"Clear this hall and claim its seal first": "请先清理此区域并领取封印。",
	"Restored & saved": "生命已恢复，进度已保存。",
	"Defeat the hall guardians to release the seal": "击败此区域的所有敌人，才能领取奖励。",
	"The shrine awaits an echo from the eastern ruins": "祭坛等待来自东侧遗迹的回响。",
	"The grove remembers. Journey complete.": "林地回响已唤醒，可以继续探索。",
	"Save failed / Progress remains in this session": "保存失败 / 进度暂保留在本次游戏中",
	"Wind barrier opened / Route saved": "风障已开启 / 通路进度已保存",
	"Returning to the last shrine...": "正在返回最近的存档点……",
	"SKY ECHO ACQUIRED": "已获得 · 天空回响",
	"Double jump unlocked": "解锁二段跳",
	"Press SPACE again in the air.": "在空中再次按空格，即可二段跳。",
	"WIND ECHO ACQUIRED": "已获得 · 风之回响",
	"Wind dash unlocked": "解锁风之冲刺",
	"K / Right shoulder to dash. No invincibility.": "按 K / 手柄右肩冲刺；冲刺没有无敌。",
	"HEART BLOOM ACQUIRED": "已获得 · 生命之花",
	"Maximum vitality +1 permanently": "生命上限永久 +1",
	"All vitality restored.": "生命已全部恢复。",
	"WATCHERS SEAL ACQUIRED": "已获得 · 守望者封印",
	"Forest shortcut + Ink Sanctum entrance unlocked": "解锁林地捷径与墨文圣所入口",
	"All vitality restored. Take the east exit to the grove.": "生命已全部恢复，从右侧出口返回林地。",
	"INK SEAL ACQUIRED": "已获得 · 墨文封印",
	"Archive return route unlocked": "解锁返回档案馆的通路",
	"All vitality restored. Take the east exit.": "生命已全部恢复，请使用右侧出口。",
	"WIND BEACON LIT": "已点亮 · 风信标",
	"Shortcut to the high grove unlocked": "解锁返回森林高台的捷径",
	"All vitality restored. Take the door on your right.": "生命已全部恢复，从右侧的门即可返回。",
	"Progress saved": "进度已保存",
	"Save failed - visit a shrine to retry": "保存失败，请到存档点重新保存"
}

static func install() -> void:
	var translation := Translation.new()
	translation.locale = "zh_CN"
	for key: String in ZH:
		translation.add_message(key,ZH[key])
	TranslationServer.add_translation(translation)

static func text(source: String) -> String:
	return String(TranslationServer.translate(source))
